server:
  port: 8080
  servlet:
    context-path: /order-management

spring:
  application:
    name: order-management
  datasource:
    url: jdbc:postgresql://localhost:5432/order-management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000  # Connection idle timeout in milliseconds
      max-lifetime: 1800000  # Maximum lifetime of a connection in milliseconds
      connection-timeout: 30000  # Maximum wait for a connection from the pool

  flyway:
    enabled: true
    locations: classpath:db/migration  # Path to migration scripts
    schemas: order_management_schema
    baseline-on-migrate: true  # Required if the schema already exists
    clean-disabled: true  # Prevents accidental schema/data deletion
    validate-on-migrate: true  # Validates migration history before applying new ones
    out-of-order: false  # Ensures migrations are applied in strict version order

  jpa:
    hibernate:
      ddl-auto: validate  # Prevents Hibernate from altering schema; Flyway manages it
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
